spring.application.name=TuTrade
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/bdTuTrade
spring.datasource.username=postgres
spring.datasource.password=prime


jwt.secret=TuTrade#Grupo4@UPC-2024$xK9mP2qLrB7nZ
jwt.expiration=86400000